server:
  port: 8080

spring:
  application:
    name: scriptsentries

  datasource:
    url: jdbc:postgresql://localhost:5433/script_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 55MB


  ai:
    openai:
      api-key:  ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai/v1

      # 'chat' MUST be indented under 'openai'
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.1
          max-tokens: 4000
      retry:
        initial-interval: 2000
        max-attempts: 1
        multiplier: 2.0

  security:
    api-key: my-secret-sentries-key-123

logging:
  level:
    com.scriptsentries: INFO
    org.springframework.ai: WARN
